title: Location Science GmbH
email: contact@locationscience.com
description: >-
  Innovative mobile applications for location-based services and solutions.
  Location Science GmbH delivers cutting-edge technology for your mobile needs.
baseurl: ""
url: "https://location-science.com"
github_username: location-science

# Build settings
theme: minima
plugins:
  - jekyll-feed
